# Generated by Django 4.1.2 on 2022-10-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
