# Generated by Django 3.2.13 on 2023-01-28 01:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='None', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('experience_in_crypto', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('if_decided_to_invest', models.CharField(choices=[('100$', '100$'), ('200$', '200$'), ('300$', '300$'), ('400$', '400$'), ('500$', '500$'), ('600$', '600$'), ('700$', '700$'), ('800$', '800$'), ('900$', '900$'), ('1000$', '1000$')], default='500$', max_length=100)),
            ],
        ),
    ]
