# Generated by Django 3.2.13 on 2023-01-28 00:02

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=homepage.models.upload_video_path)),
            ],
        ),
    ]
