# Generated by Django 4.1.2 on 2022-10-11 21:49

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=homepage.models.upload_video_path),
        ),
    ]
